@host = https://localhost
@port = 5289

@Restaurants.API_HostAddress = https://localhost:7199

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###
