@host = https://localhost
@port = 5289
@token = CfDJ8CT6qQZkr71OvgSgL2Vc9pqQ1w0P6Ecb4-b7p76sVSUf3A3WvnbC-totUb-vVhT5GYKZ0PuN9ERzPBSdtRUFoH0VReCTEmlrOcSVqyWGapSzVgukPDixX07vHn4Z2a4JmKKfQejocRyrJwBQOKTLfV_xBIN8lImLud-qFklU_p7-2q6B1fK_ywynggv-C6MiCHuoj9COIVoKRQxv1ugPq-m87fbPVIUOMLmVpXoz7HLJzCMgqSaDncDIMT6THRezXeQrV2zNV_Dgb_AbpNSJJP8b6IowBBtsW2QZUVyrHXzd8mbGkUbE0kr_aXkswbeE62aeA8iUyw6J_YgC21KkWHYYtEalJ7bbE7We-LgNxjz1vPlbwN1l9Jm4MoUdw5dFtpaz9c0qW-BzKWwhmsF-9ZrQLvnKliqu4hVIEiMQnOxD4CV3dp7yYI8j2Y44njxIrzdiK84hxFl5KTCteA1oDWrJs3IGsUqaSSZJGxnubdCHzn0nbbCcWPNvzM66V7QQT34_Hu8ujXm-K_GdH3y_tjC4ic9jfylSdRPYzalmq2it4BueKPYJOCwSkPHUc28SrQzyJgYyPSUbMyuOVICiioqsTQx4Q_dzVUYkn3KWdCfIrBeqxST86PiqzQUbzClpGsthMfXsvEbUjVJdDxyYNvRoi1KH5sTyFwn69IrMH4iNGh0v-al0yEKz4rcRqDaIHA

@Restaurants.API_HostAddress = https://localhost:7199

GET {{Restaurants.API_HostAddress}}/api/restaurants
# Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
      "Name": "Owner2 restaurant2",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5

###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json

{
      "Name": "restaurant2",
      "Description": "A dishes.",
      "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
   "Name": "Spaghetti Bolognese",
   "Description": "Classic Italian pasta dish with rich meat sauce",
   "Price": 12.99,
   "KiloCalories": 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/3

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/54/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
   "email": "testuser@test.com",
   "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
   "email": "testuser@test.com",
   "password": "Password1!"
}
 
