@host = https://localhost
@port = 5289
@token = CfDJ8CT6qQZkr71OvgSgL2Vc9ppdP2Y7fzYtf8L1ZwReiP01PTGdgeT9FmP1vdpdGOqCiR0KroBPgZug5crhlYn2j5YR740DrMuyixCLHfN0ppy4azTa0JjJqjq-i3muNlRpBfbj0QoYZVc2QDrPCB58Bznxt7EP7Fda371kGJ7bjWQI_oB0LYS2rPxUq3W11G05RWLLN1UV8NJYashDoJG3a15CklVq3iA4R7MPSVLtKooxu7AJjIINpvjPKYhBEjIZIt_FpGHdT9piRf7MYem4rDB-BGNg-KgG4Vla80VEpR9C5B7KZfMMvixUwvEJlJ6RNlQVNVGJ_CvZbwPHNEf4gWwwPTyNuoT8FLDoLP6F6WpT2Vl3zB1Us-0HWk1CDhy_kDwdrfPXZjdxraV-V9k6NTiAofmVa1tMnvG8U33b8HtEpOw4VcEXUDcvzqiU3Rsm-SrODTCnqabp7yG54_oocGzOhC9YHobZupVmKHFKratm1NWd1Jueh6Q1Nmf8umAqnLz2RbrlToeIxHVeR96FNnOuEoe2s0y7Poc5BcP-1gEm9MlrceCJ6mCTDi84Dp3uLM1GhO0ERP6dJczD90OU5tS-zffXRQ0_om_NA2pcQbi4s9FnU4WS5Q3RpwxWsf0MdjvZcxpAmGt1QR4ZCSnX74s_jP6eyJ8O4cW7StiZsHUGJurhPmnE_h0rvf1E1OdtKMIEnxLVmC-VHCAnqVqX7yuqr8kfij60jsJuPgKTqG8mumG4AI15WKt4eoZhW6an1xyae-I0_C4W7_mi2r21Fl4zsN2JwyUEyYVJUtSNikbw

@Restaurants.API_HostAddress = https://localhost:7199

GET {{Restaurants.API_HostAddress}}/api/restaurants?pageSize=3&pageNumber=1
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
      "Name": "Owner restaurant",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5

###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/8
Content-Type: application/json
Authorization: Bearer {{token}}

{
      "Name": "Updated name",
      "Description": "A dishes.",
      "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Authorization: Bearer {{token}}

Content-Type: application/json

{
   "Name": "Spaghetti Bolognese",
   "Description": "Classic Italian pasta dish with rich meat sauce",
   "Price": 12.99,
   "KiloCalories": 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/3

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/54/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
   "email": "owner2@test.com",
   "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
   "email": "owner2@test.com",
   "password": "Password1!"
}
 
###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userEmail" : "owner2@test.com",
  "roleName": "Owner"
}

###
